[[redirects]]
  from = "https://www.emrs.ae/*"
  to = "https://emrs.ae/:splat"
  status = 301
  force = true

[build]
  publish = "dist"
  command = "npm run build"

# Redirect all SPA routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security & SEO
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Type = "text/html; charset=UTF-8"


[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"




# SEO Redirect for typo URL
[[redirects]]
  from = "/blog/how-to-choose-ambance-service"
  to = "/blog/how-to-choose-ambulance-service"
  status = 301
  force = true
