[build]
  publish = "dist"
  command = "npm run build"

# Configure Checklinks plugin (installed via UI) to ignore false positives
[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
    skipPatterns = [
      "https://fonts.gstatic.com",
      "https://fonts.googleapis.com",
      "https://www.googletagmanager.com"
    ]


# Redirect all SPA routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security & SEO
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"
